### ISSUE TITLE
Hijackedstack status error

### ISSUE THREAD

**Issue by hypzzz** [aave/flashloan-box#23]
when i run the flash loan part it gives me the following error

truffle(kovan)> await f.flashloan("0xd0a1e359811322d97991e03f863a0c30c2cf029c")
Uncaught:
StatusError: Transaction: 0xeb5e5353158f07d0b1c85e4cb64f3ea426e26908044ffb27e6c9c8f0efcea8f4 exited with an error (status 0).
    at evalmachine.<anonymous>:1:11
    at evalmachine.<anonymous>:2:49
    at sigintHandlersWrap (vm.js:273:12)
    at Script.runInContext (vm.js:140:14)
    at runScript (C:\Users\alexx\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\console.js:270:1)
    at Console.interpret (C:\Users\alexx\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\console.js:285:1)
    at bound (domain.js:416:15)
    at REPLServer.runBound [as eval] (domain.js:427:12)
    at REPLServer.onLine (repl.js:819:10)
    at REPLServer.emit (events.js:376:20)
    at REPLServer.emit (domain.js:470:12)
    at REPLServer.Interface._onLine (readline.js:342:10)
    at REPLServer.Interface._line (readline.js:671:8)
    at REPLServer.Interface._ttyWrite (readline.js:1015:14) {
  tx: '0xeb5e5353158c9c8f0efcea8f4',
  receipt: {
    blockHash: '0xf84ec886c2c6c80930a0bd178c44609afdfd8378681143a8f2026ccfe77705e4',
    blockNumber: 25367850,
    contractAddress: null,
    cumulativeGasUsed: 117552,
    from: '0x7ec63cc91f',
    gasUsed: 62524,
    logs: [],
    logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
    status: false,
    to: '0xb6cf18a9f7e8543d1d23058a979c1cd7ddd0f084',
    transactionHash: '0xeb5e5353158f07d0b1c85e4cb64f3ea426e26908044ffb27e6c9c8f0efcea8f4',
    transactionIndex: 1,
    rawLogs: []
  },
  reason: undefined,
  hijackedStack: 'StatusError: Transaction: 0xeb5e5353158f07d0b1c85e4cb64f3ea426e26908044ffb27e6c9c8f0efcea8f4 exited with an error (status 0). \n' +
    '     Please check that the transaction:\n' +
    '     - satisfies all conditions set by Solidity `require` statements.\n' +
    '     - does not trigger a Solidity `revert` statement.\n' +
    '\n' +
    '    at Object.receipt (C:\\Users\\alexx\\AppData\\Roaming\\npm\\node_modules\\truffle\\build\\webpack:\\packages\\contract\\lib\\handlers.js:128:1)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n' +
    '    at Function.start (C:\\Users\\alexx\\AppData\\Roaming\\npm\\node_modules\\truffle\\build\\webpack:\\packages\\contract\\lib\\override.js:49:1)'
}
truffle(kovan)>

I dont understand why im getting a hijack error?

**Comment by chishiq** [comment]
i meet the same problem, have you already handle it?
