### ISSUE TITLE
Compilation error after fresh install

### ISSUE THREAD

**Issue by jmlon** [aave/flashloan-box#4]
Hi, I am just following the instructions on Aave's documentation page, but I run into the following error.
Here is the environment I am working on:
Windows 10
```
PS D:\GIT\temp> node -v
v12.16.3
PS D:\GIT\temp> npm -v
6.14.4
PS D:\GIT\temp> truffle version
Truffle v5.1.0 (core: 5.1.0)
Solidity v0.5.12 (solc-js)
Node v12.16.3
Web3.js v1.2.2
```
The installation of the truffle box is successful:
```
truffle unbox aave/flashloan-box
...
Unbox successful. Sweet!
```
And right after that, compilation throws the following error:
```
  PS D:\GIT\temp> truffle compile
  Error: Mnemonic invalid or undefined
      at checkBIP39Mnemonic (D:\GIT\temp\node_modules\@truffle\hdwallet-provider\src\index.ts:74:15)
      at new HDWalletProvider (D:\GIT\temp\node_modules\@truffle\hdwallet-provider\src\index.ts:104:23)
      at Object.<anonymous> (D:\GIT\temp\truffle-config.js:17:16)
      at Module._compile (internal/modules/cjs/loader.js:1133:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
      at Module.load (internal/modules/cjs/loader.js:977:32)
      at Function.Module._load (internal/modules/cjs/loader.js:877:14)
      at Module.require (internal/modules/cjs/loader.js:1019:19)
      at Object.require (internal/modules/cjs/helpers.js:77:18)
      at Function.load (C:\Users\Jorge\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\config\dist\index.js:145:1)
      at Function.detect (C:\Users\Jorge\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\config\dist\index.js:134:1)
      at Object.run (C:\Users\Jorge\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\commands\compile.js:53:1)
      at Command.run (C:\Users\Jorge\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\command.js:136:1)
      at Object.<anonymous> (C:\Users\Jorge\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\cli.js:52:1)
      at __webpack_require__ (C:\Users\Jorge\AppData\Roaming\npm\node_modules\truffle\build\webpack:\webpack\bootstrap 45f436e53fa694e98811:19:1)
      at C:\Users\Jorge\AppData\Roaming\npm\node_modules\truffle\build\webpack:\webpack\bootstrap 45f436e53fa694e98811:65:1
      at Object.<anonymous> (C:\Users\Jorge\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:71:10)
      at Module._compile (internal/modules/cjs/loader.js:1133:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
      at Module.load (internal/modules/cjs/loader.js:977:32)
      at Function.Module._load (internal/modules/cjs/loader.js:877:14)
      at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
      at internal/main/run_main_module.js:18:47
  Truffle v5.1.0 (core: 5.1.0)
  Node v12.16.3
```

Seems to be an issue with the @truffle/hdwallet-provider, but manual reinstallatio of the module and its dependencies hasn't solved the problem.

A temporary solution I found was to comment out all references to `HDWalletProvider` in `truffle-config.js`.

Any help is greatly appreciated.

**Comment by mrdavey** [comment]
Hey @jmlon . Sorry for the late reply. It looks like you didn't set up your `.env` properly, as `truffle-config.js` refers to `process.env.DEPLOYMENT_ACCOUNT_KEY`.
I hope that helps! Feel free to reopen or join our discord (https://aave.com/discord) to discuss further.
